services:
  frontend:
    build:
      context: ./frontend
      args:
        HOST_IP: ${HOST_IP}
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_JSONWEB_TOKEN=${AZURE_JSONWEB_TOKEN}